// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/24/2024, 8:21:12 AM
const configMerger = require("/Users/christina/GitHub/europe-climate-reporting-2/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/christina/GitHub/europe-climate-reporting-2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christina/GitHub/europe-climate-reporting-2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christina/GitHub/europe-climate-reporting-2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christina/GitHub/europe-climate-reporting-2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christina/GitHub/europe-climate-reporting-2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christina/GitHub/europe-climate-reporting-2/plugins/**/*.{js,ts,mjs}","/Users/christina/GitHub/europe-climate-reporting-2/composables/**/*.{js,ts,mjs}","/Users/christina/GitHub/europe-climate-reporting-2/utils/**/*.{js,ts,mjs}","/Users/christina/GitHub/europe-climate-reporting-2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/christina/GitHub/europe-climate-reporting-2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/christina/GitHub/europe-climate-reporting-2/app.config.{js,ts,mjs}"] }));

module.exports = config
